apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: test-4-1
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhn-support-csears/test-4-1:364a03fe9ce3a94692db7f404a5e1fa605423026@sha256:1fc2fd456aadcae6ad88388a75ed92c622b9aa3c8856bd2ce6f3a66161cb192f
          name: container-image
